### ISSUE TITLE
Meta-question about supported versions for plugins

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-astropy#1]
We anticipate that our top-level pytest plugins will be of general use outside the astronomy community. This means we need to make a decision about versions: while astropy itself may only support Py3 in the near future, should we continue to support Py2 in the plugins? Also, what minimum version of pytest should we support? Astropy core has moved to support a minimum of 3.1, but there don't appear to be any technical reason why we couldn't support earlier versions for the plugins.

@astrofrog, @eteq, @bsipocz, @pllim

**Comment by pllim** [comment]
IMHO

1. We should follow pytest's guideline on Python 2 support (only for the plugins, not astropy itself).
2. For simplicity, there is no reason to support `pytest<3.1`. If they work with older pytest, then it is a bonus but we should not waste too much time on it.

**Comment by bsipocz** [comment]
I agree with @pllim on both points.

**Comment by astrofrog** [comment]
Same here, I agree with @pllim

**Comment by drdavella** [comment]
I can't find any indication that pytest plans to deprecate support for Py2.6+ in the near future. I don't think we should bend over backwards to support 2.7 in the plugins, but we shouldn't necessarily explicitly disallow it either.

As for pytest versions, all of these plugins were working on 2.8, so maybe that should be our earliest officially supported version? Again, we won't bend over backwards to maintain compatibility, though.

**Comment by drdavella** [comment]
Closing since I think this question has been answered.
