### ISSUE TITLE
Move pytest header here?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-astropy#15]
https://github.com/astropy/astropy/blob/0f7b5e840f2ce9899c44f9aaf05cca211791758f/astropy/tests/plugins/display.py#L31

As suggested by @drdavella , cc @bsipocz .

**Comment by bsipocz** [comment]
And also make the astropy specific stuff optional, e.g. helpers, or the Astropy options for remote-data.

**Comment by astrofrog** [comment]
Arguably we could move all the remaining custom plugins here. I'm trying to remember why we didn't.

**Comment by drdavella** [comment]
I seem to remember thinking that the remaining plugins were likely only useful to `astropy` core, but that's clearly not true in this case.

**Comment by bsipocz** [comment]
sorry 😊

**Comment by astrofrog** [comment]
I'm working on this now!
