### ISSUE TITLE
What's the point of this package?

### ISSUE THREAD

**Issue by mcepl** [astropy/pytest-astropy#16]
Couldn't this project be replaced by one ``test-requirements.txt`` file in the https://github.com/astropy/astropy repo?

**Comment by drdavella** [comment]
@mcepl it could, but the point is to have a single dependency for *all* affiliated packages (and any other package) that would like to include all of these plugins.

**Comment by astrofrog** [comment]
We may also include astropy-project specific plugins here that currently live in astropy.tests

**Comment by mcepl** [comment]
Just that I am an openSUSE maintainer, and this packages makes my life seemingly uselessly complicated. Anyway. Thank you for explanation.
