### ISSUE TITLE
Transition all astropy pytest- packages to use setup.cfg

### ISSUE THREAD

**Issue by astrofrog** [astropy/pytest-astropy#17]
*Rather than open an issue in each repo, I thought I'd open one issue here for all pytest plugins in the astropy organization.*

Since setuptools 30.3.0, it's possible to define most of the metadata for ``setuptools`` in ``setup.cfg`` instead of ``setup.py``. This is preferable since the metadata is then more structured and parsable. Here's an example of how to do this: https://github.com/astropy/sphinx-automodapi/pull/62 - I'm not sure whether the warning about the setuptools version is really needed though.

**Comment by pllim** [comment]
> Rather than open an issue in each repo

Why not? 😉  *cough* batchpr *cough*

**Comment by pllim** [comment]
Fixed in #29
