### ISSUE TITLE
Update "Homepage" on PyPI for the plugins

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-astropy#18]
Currently it points to https://astropy.org causing a "your connection is not secure". Apparently it's a known issue (https://github.com/astropy/astropy.github.com/issues/264), but for now it would make sense to either update the link to http or to point to the plugins github (I was looking for the github link to save me some typing, so it may make more sense than linking to the central page).

**Comment by eteq** [comment]
I *think* I've done what I need to do to fix this.  It's already working on https://www.astropy.org, and http://astropy.org redirects to https://www.astropy.org now.  The one currently not-working step is https://astropy.org, but I *think* that should be working in another hour or so once the certificate gets renewed.  If not I'll try again and see...

**Comment by pllim** [comment]
This is 3 hours later. On Chrome on Windows 10, I get this:

```
Your connection is not private

Attackers might be trying to steal your information from astropy.org
(for example, passwords, messages, or credit cards). Learn more

NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by eteq** [comment]
Grr, same here.  Well, at least I got rtd working...  (astropy/astropy#8569) maybe I just need to do something special to re-issue the ssl certificate from GitHub?  More testing needed...

**Comment by astrofrog** [comment]
Seems fixed now, thanks!
