### ISSUE TITLE
Add pytest-astropy-header here?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-astropy#22]
xref astropy/astropy#9214

**Comment by astrofrog** [comment]
Done already! (And released)

**Comment by pllim** [comment]
I see that you pushed the commit to add it as dependency. I have a PR open at #23 to add it to README. But I don't see a new GitHub release out, althought `pip install pytest-astropy` does pull in 0.6 and get `pytest-astropy-header` installed.

**Comment by bsipocz** [comment]
I suppose the he didn't tag/pushed the tag just did an sdist to pypi? we still use pypi for the releases, rather than GH, I suppose.

**Comment by pllim** [comment]
But it's misleading because the previous releases have GitHub tags.

**Comment by astrofrog** [comment]
I need to push the tag, will do tomorrow (I forgot before)

**Comment by astrofrog** [comment]
Tag pushed, so I think we are all good here
