### ISSUE TITLE
conda install doesn't pick up latest version on old python

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-astropy#28]
On python3.5 the latest pytest-astropy releases are not being picked up, it stuck on installing the 0.4.0 version, that was packages up before we switched to noarch.
https://travis-ci.org/astroML/astroML/jobs/631161062#L3213

The workaround is trivial for that travis job, but this demonstrates an issue that users might run into, too.

**Comment by pllim** [comment]
`conda` pretty much abandoned Python 3.5. There are plenty of problems with other packages too with conda + Python 3.5 combo, not just this (meta)package.

**Comment by bsipocz** [comment]
yeah, fair enough. Hindsight I should have just switched straight to tox rather than go via ci-helpers.

**Comment by pllim** [comment]
Or drop Python 3.5? 😬

**Comment by bsipocz** [comment]
Would be nice,  but I can't, we said 3.5+ in the book, so I should stick with that for a while now.

**Comment by pllim** [comment]
Python 3.5 support is dropped in #29, so closing as won't fix.
