### ISSUE TITLE
Should this package be distributed via conda?

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-astropy#3]

**Comment by bsipocz** [comment]
Would be great to have a conda package. ``pytest-astropy`` cannot be installed with ``--no-deps``, so it makes hacky for ci-helpers to make sure it doesn't update dependencies installed by conda with a pinned version number.

**Comment by larrybradley** [comment]
:+1:

**Comment by drdavella** [comment]
It sounds like this requires each of the individual plugin packages to also be distributed through conda. Is `conda-forge` the right channel for this? Should we publish on `astroconda` as well?

**Comment by bsipocz** [comment]
I vote for conda-forge, for multiple reasons. 1) these are generic packages, so makes sense to make them available at the standard places, astroconda is very separate from that (though you can and should copy the packages over if you think it's useful to be there, too).
2) From conda-forge we have the machinery set up and running to copy and distribute astropy related and required packages on the ``astropy`` channel, too.

**Comment by astrofrog** [comment]
+1 to conda-forge

**Comment by bsipocz** [comment]
We need this to happy to be able to package the new astropy 3.0 release, so it became quite critical.

**Comment by drdavella** [comment]
This is being addressed by https://github.com/conda-forge/staged-recipes/pull/5154.

**Comment by drdavella** [comment]
This package and all of its dependencies are now available via `conda-forge`.

**Comment by bsipocz** [comment]
Actually they are also available on defaults atm, given that `pytest-astropy` was listed as an astropy dependency in its recipe.
