### ISSUE TITLE
Remove attr version pinning when new pip resolver is released

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-astropy#36]
`attr` is an indirect dependency, so should be removed once the pip resolver handles it properly.

See convo here https://github.com/astropy/pytest-astropy/pull/30#issuecomment-640136589

**Comment by pllim** [comment]
Thanks for following up on this!

Do you know where that pip resolver PR is or what version of pip we should be looking out for?

**Comment by bsipocz** [comment]
It's in fact released and they are soliciting feedback:
https://github.com/pypa/pip/issues/4745#issuecomment-635302302

**Comment by pllim** [comment]
It is 2024 now... Any progress upstream? 👀

**Comment by bsipocz** [comment]
upstream: there is the new solver, but I also keep running into silent upgrades of packages so even if new options are added, we don't necessarily use them (see: for CI I would prefer pip to error out rather than to upgrade a version that is otherwise explicitly asked for, or is already installed)

Whether we can remove the attr pin? I have no idea but would say very likely we can as the current pin requests an almost 5 year old version.
