### ISSUE TITLE
Add pytest-mpl back as a dependency here

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-astropy#4]
This would allow `pytest-mpl` to be automatically distributed with astropy's other test dependencies.

**Comment by bsipocz** [comment]
Oh, and pytest-arraydiff, too

**Comment by astrofrog** [comment]
👍

**Comment by pllim** [comment]
We took `pytest-mpl` back out because it pulls in `matplotlib` as a required dependency, which is undesirable. Once @astrofrog fixes that to make `matplotlib` optional again, it should be added back in (again).

xref https://github.com/astropy/astropy/pull/9726#discussion_r367859664

**Comment by astrofrog** [comment]
Also xref https://github.com/matplotlib/pytest-mpl/pull/87

**Comment by pllim** [comment]
Is it time to revisit this or should we close it?

**Comment by astrofrog** [comment]
We can revisit, I think matplotlib should no longer be a dependency

**Comment by pllim** [comment]
Are you sure? matplotlib is still required:

https://github.com/matplotlib/pytest-mpl/blob/2611bd020b523ab4fff1c9fa7db936b68dad7113/setup.cfg#L30

**Comment by pllim** [comment]
As of today, matplotlib is still pulled in. FYI.

```
$ pip install pytest-mpl
Installing collected packages: matplotlib, pytest-mpl
Successfully installed matplotlib-3.4.3 pytest-mpl-0.13
```

**Comment by Cadair** [comment]
(Puts on pytest-mpl maintainer hat)

I really don't think that not depending on matplotlib for pytest-mpl makes *any* sense at all. It's required to function.

**Comment by bsipocz** [comment]
I think this issue should be closed as won't fix. If mpl is pulled in to CI, when it's in fact optional dependency for many packages, then this meta package will become unfit for its main purpose of helping CI.

**Comment by astrofrog** [comment]
I agree with @bsipocz that this plugin should not be pulled in by default, packages should just install this plugin when needed.
